### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/rp2040-dmxsun#41]
> It's also easily backronymable, DMX Sixteen UNiverses laughing !

Nice one, didn't even think of it! Want it in the Readme? ;)

_Originally posted by @kripton in https://github.com/OpenLightingProject/rp2040-dongle/issues/34#issuecomment-1010292429_

I'll leave that bit up to you either way.

But maybe if it's now called dmxsun the repo should be renamed to match so people can find it? Unless you're going down the route we did with Ja Rule where the software and hardware had different names?

**Comment by kripton** [comment]
True, I planned to rename it but wasn't sure if I'm allowed to rename a repo in the organisation and how GitHub handles renames. Meanwhile, I've read https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository, just tried it and it worked. So, renaming done :)
